theme: jekyll-theme-midnight
title: [Ground truth labels for Amazon movie reviews dataset]
description: [A new labeled data source available for your machine learning projects]
show_downloads: ["true"]
google_analytics: [UA-102276774-1]
